# font configurations
FONT = "Verdana"
FONTCOLOR = "#2c3e50"

# ui colors
BACKGROUND_COLOR = "#f7f7f7"
SIDEBAR_COLOR = "#ecf0f1"
HIGHLIGHT_COLOR = '#54a6ff'
SLIDER_BACKGROUND = SIDEBAR_COLOR
SLIDER_BAR_COLOR = "#95a5a6"

# plot configurations
DOTCOLOR = '#e63704'
DOTSIZE = 4
DOTALPHA = 0.8
SHADOWCOLOR = '#ffbb38'
SHADOWALPHA = 0.4
VIDEOALPHA = 0.75
MICCOLOR = HIGHLIGHT_COLOR
MICLINECOLOR = FONTCOLOR 
MICSIZE = 3
MICALPHA = 1
PLOT_BACKGROUND_COLOR = BACKGROUND_COLOR
ORIGINLENGTH = 0.15
ORIGINCOLOR = HIGHLIGHT_COLOR
ORIGINLINEWIDTH = 1
ORIGINHEADSIZE = 8

# ui and plot positions and dimensions
FIG_WIDTH = 800
FIG_HEIGHT = 600
SIDEBAR_WIDTH = 300


start_text = "Start"
stop_text = "Stop"